title: Riccardo Barazzotto's Portfolio'
author_name: Riccardo Barazzotto
description: Game Developer and C++ Specialist.
url: "https://tuonome.github.io" 

collections:
  projects:
    output: true
    permalink: /projects/:path/