title: Mario Rossi Portfolio
author_name: Mario Rossi
description: Game Developer & Unity Specialist. Creo mondi interattivi e sistemo bug impossibili.
url: "https://tuonome.github.io" 

collections:
  projects:
    output: true
    permalink: /projects/:path/